---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - submariner.io
  resources:
  - clustersetnetworkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - submariner.io
  resources:
  - clustersetnetworkpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - submariner.io
  resources:
  - clustersetnetworkpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - submariner.io
  resources:
  - remotepods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - submariner.io
  resources:
  - remotepods/finalizers
  verbs:
  - update
- apiGroups:
  - submariner.io
  resources:
  - remotepods/status
  verbs:
  - get
  - patch
  - update
